### ISSUE TITLE
Move dev planning from Trello to Github issues.

### ISSUE THREAD

**Issue by edrex** [edrex/pillowfork#1]
## Reasons
- Integration with commits and branches
- Much better visibility for potential contributors
## Tasks
- [x] Create an issue for this task
- [x] Port milestones
- [x] Port labels 
- [x] Port completed tasks
- [x] Port current tasks
- [x] Port icebox tasks
